### ISSUE TITLE
I get this error message

### ISSUE THREAD

**Issue by JackPlaysGames0510** [BillyCurtis/OpenSpotifySafariExtension#4]
I get an error message when it open a Spotify link open the link but if the app is already open it works fine
![IMG_0680](https://github.com/BillyCurtis/OpenSpotifySafariExtension/assets/48178959/7c35e3e9-4d2a-4e7a-8966-dd246e3d692f)

**Comment by BillyCurtis** [comment]
This is probably an issue with the EeveeSpotify tweak since all links are handled by it. 

I'm guessing since the app was closed when it was opened from a link Spotify handled before EeveeSpotify did, and since Spotify doesn't recognise /eevee/ in the link, it's giving you that error. 

Maybe @whoeevee can fix this?

**Comment by JackPlaysGames0510** [comment]
talk to them and i don't think they can't be fix

**Comment by whoeevee** [comment]
The issue is, when the app is closed, the method `openURLContexts` that EeveeSpotify hooks for opening links is not called. Instead, there is `willConnectToSession:options:` and Spotify is not recognizing /eevee/ in the link provided by OpenSpotifySafariExtension. I initially didn't implement hook of this method because Orion was giving me errors, and there were some problems with WindowHelper.

But now, I've fixed that by hooking the `URL` method of UIOpenURLContext that is called when you open the link both when the app is launched or not. It checks the link, and if it's from OpenSpotifySafariExtension, replaces with the original Spotify link. Works perfectly, see: https://github.com/whoeevee/EeveeSpotify/commit/2922687

**Comment by JackPlaysGames0510** [comment]
oh I see this is interesting I'm glad you found an update for this can't wait for the update
